### ISSUE TITLE
006v2 - Accounts

### ISSUE THREAD

**Issue by imaron85** [PhilippJakob/CE22#20]
### Account creation (server-side)
- [ ] [ Table for Accounts](https://github.com/PhilippJakob/CE22/issues/21)
<table>
<tr>
<th>Account</th><td>id</td><td>type</td><td>username</td><td>password</td><td>fistname</td><td>lastname</td><td>class</td>
</tr>
</table>

 - [ ] [Create Account Class to work with Accounts](https://github.com/PhilippJakob/CE22/issues/22)
    - Attributes derrived from DB

### UI

- [ ] Account related UI
    - [ ] [Register](https://github.com/PhilippJakob/CE22/issues/23)
        - username
        - firstname
        - lastname
        - class
        - password
    - [ ] [Log in](https://github.com/PhilippJakob/CE22/issues/24)
        - username
        - password
    - [ ] [Log out](https://github.com/PhilippJakob/CE22/issues/25)
    - [ ] [Admin Panel for editing Accounts](https://github.com/PhilippJakob/CE22/issues/26)
        - Change type
        - Edit name
        - Edit class
